server:
  port: ${SERVER_PORT:8094} 
  
grpc: 
  server:
    port: ${GRPC-SERVER-PORT:9099} 
    
spring:
  jackson:
    deserialization:
      wrap-exceptions: false
  main:
    allow-circular-references: true
    