// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductServer.proto

package com.grpcserver.product;

public final class ProductServer {
  private ProductServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProductOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Product)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 purchase_item = 1;</code>
     */
    int getPurchaseItem();

    /**
     * <code>string productname = 2;</code>
     */
    java.lang.String getProductname();
    /**
     * <code>string productname = 2;</code>
     */
    com.google.protobuf.ByteString
        getProductnameBytes();

    /**
     * <code>string productbrand = 3;</code>
     */
    java.lang.String getProductbrand();
    /**
     * <code>string productbrand = 3;</code>
     */
    com.google.protobuf.ByteString
        getProductbrandBytes();

    /**
     * <code>double productprice = 4;</code>
     */
    double getProductprice();

    /**
     * <code>string productdescription = 5;</code>
     */
    java.lang.String getProductdescription();
    /**
     * <code>string productdescription = 5;</code>
     */
    com.google.protobuf.ByteString
        getProductdescriptionBytes();

    /**
     * <code>int32 productquantity = 6;</code>
     */
    int getProductquantity();

    /**
     * <code>string productexpirationdate = 8;</code>
     */
    java.lang.String getProductexpirationdate();
    /**
     * <code>string productexpirationdate = 8;</code>
     */
    com.google.protobuf.ByteString
        getProductexpirationdateBytes();
  }
  /**
   * Protobuf type {@code Product}
   */
  public  static final class Product extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Product)
      ProductOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Product.newBuilder() to construct.
    private Product(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Product() {
      purchaseItem_ = 0;
      productname_ = "";
      productbrand_ = "";
      productprice_ = 0D;
      productdescription_ = "";
      productquantity_ = 0;
      productexpirationdate_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Product(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              purchaseItem_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              productname_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              productbrand_ = s;
              break;
            }
            case 33: {

              productprice_ = input.readDouble();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              productdescription_ = s;
              break;
            }
            case 48: {

              productquantity_ = input.readInt32();
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              productexpirationdate_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpcserver.product.ProductServer.internal_static_Product_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpcserver.product.ProductServer.internal_static_Product_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpcserver.product.ProductServer.Product.class, com.grpcserver.product.ProductServer.Product.Builder.class);
    }

    public static final int PURCHASE_ITEM_FIELD_NUMBER = 1;
    private int purchaseItem_;
    /**
     * <code>int32 purchase_item = 1;</code>
     */
    public int getPurchaseItem() {
      return purchaseItem_;
    }

    public static final int PRODUCTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object productname_;
    /**
     * <code>string productname = 2;</code>
     */
    public java.lang.String getProductname() {
      java.lang.Object ref = productname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productname_ = s;
        return s;
      }
    }
    /**
     * <code>string productname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProductnameBytes() {
      java.lang.Object ref = productname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCTBRAND_FIELD_NUMBER = 3;
    private volatile java.lang.Object productbrand_;
    /**
     * <code>string productbrand = 3;</code>
     */
    public java.lang.String getProductbrand() {
      java.lang.Object ref = productbrand_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productbrand_ = s;
        return s;
      }
    }
    /**
     * <code>string productbrand = 3;</code>
     */
    public com.google.protobuf.ByteString
        getProductbrandBytes() {
      java.lang.Object ref = productbrand_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productbrand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCTPRICE_FIELD_NUMBER = 4;
    private double productprice_;
    /**
     * <code>double productprice = 4;</code>
     */
    public double getProductprice() {
      return productprice_;
    }

    public static final int PRODUCTDESCRIPTION_FIELD_NUMBER = 5;
    private volatile java.lang.Object productdescription_;
    /**
     * <code>string productdescription = 5;</code>
     */
    public java.lang.String getProductdescription() {
      java.lang.Object ref = productdescription_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productdescription_ = s;
        return s;
      }
    }
    /**
     * <code>string productdescription = 5;</code>
     */
    public com.google.protobuf.ByteString
        getProductdescriptionBytes() {
      java.lang.Object ref = productdescription_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productdescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCTQUANTITY_FIELD_NUMBER = 6;
    private int productquantity_;
    /**
     * <code>int32 productquantity = 6;</code>
     */
    public int getProductquantity() {
      return productquantity_;
    }

    public static final int PRODUCTEXPIRATIONDATE_FIELD_NUMBER = 8;
    private volatile java.lang.Object productexpirationdate_;
    /**
     * <code>string productexpirationdate = 8;</code>
     */
    public java.lang.String getProductexpirationdate() {
      java.lang.Object ref = productexpirationdate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productexpirationdate_ = s;
        return s;
      }
    }
    /**
     * <code>string productexpirationdate = 8;</code>
     */
    public com.google.protobuf.ByteString
        getProductexpirationdateBytes() {
      java.lang.Object ref = productexpirationdate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productexpirationdate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (purchaseItem_ != 0) {
        output.writeInt32(1, purchaseItem_);
      }
      if (!getProductnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, productname_);
      }
      if (!getProductbrandBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, productbrand_);
      }
      if (productprice_ != 0D) {
        output.writeDouble(4, productprice_);
      }
      if (!getProductdescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, productdescription_);
      }
      if (productquantity_ != 0) {
        output.writeInt32(6, productquantity_);
      }
      if (!getProductexpirationdateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, productexpirationdate_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (purchaseItem_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, purchaseItem_);
      }
      if (!getProductnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, productname_);
      }
      if (!getProductbrandBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, productbrand_);
      }
      if (productprice_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, productprice_);
      }
      if (!getProductdescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, productdescription_);
      }
      if (productquantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, productquantity_);
      }
      if (!getProductexpirationdateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, productexpirationdate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpcserver.product.ProductServer.Product)) {
        return super.equals(obj);
      }
      com.grpcserver.product.ProductServer.Product other = (com.grpcserver.product.ProductServer.Product) obj;

      boolean result = true;
      result = result && (getPurchaseItem()
          == other.getPurchaseItem());
      result = result && getProductname()
          .equals(other.getProductname());
      result = result && getProductbrand()
          .equals(other.getProductbrand());
      result = result && (
          java.lang.Double.doubleToLongBits(getProductprice())
          == java.lang.Double.doubleToLongBits(
              other.getProductprice()));
      result = result && getProductdescription()
          .equals(other.getProductdescription());
      result = result && (getProductquantity()
          == other.getProductquantity());
      result = result && getProductexpirationdate()
          .equals(other.getProductexpirationdate());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PURCHASE_ITEM_FIELD_NUMBER;
      hash = (53 * hash) + getPurchaseItem();
      hash = (37 * hash) + PRODUCTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getProductname().hashCode();
      hash = (37 * hash) + PRODUCTBRAND_FIELD_NUMBER;
      hash = (53 * hash) + getProductbrand().hashCode();
      hash = (37 * hash) + PRODUCTPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getProductprice()));
      hash = (37 * hash) + PRODUCTDESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getProductdescription().hashCode();
      hash = (37 * hash) + PRODUCTQUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getProductquantity();
      hash = (37 * hash) + PRODUCTEXPIRATIONDATE_FIELD_NUMBER;
      hash = (53 * hash) + getProductexpirationdate().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpcserver.product.ProductServer.Product parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcserver.product.ProductServer.Product parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcserver.product.ProductServer.Product parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcserver.product.ProductServer.Product parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcserver.product.ProductServer.Product parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcserver.product.ProductServer.Product parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcserver.product.ProductServer.Product parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcserver.product.ProductServer.Product parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpcserver.product.ProductServer.Product parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.grpcserver.product.ProductServer.Product parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpcserver.product.ProductServer.Product parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcserver.product.ProductServer.Product parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpcserver.product.ProductServer.Product prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Product}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Product)
        com.grpcserver.product.ProductServer.ProductOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpcserver.product.ProductServer.internal_static_Product_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpcserver.product.ProductServer.internal_static_Product_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpcserver.product.ProductServer.Product.class, com.grpcserver.product.ProductServer.Product.Builder.class);
      }

      // Construct using com.grpcserver.product.ProductServer.Product.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        purchaseItem_ = 0;

        productname_ = "";

        productbrand_ = "";

        productprice_ = 0D;

        productdescription_ = "";

        productquantity_ = 0;

        productexpirationdate_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpcserver.product.ProductServer.internal_static_Product_descriptor;
      }

      @java.lang.Override
      public com.grpcserver.product.ProductServer.Product getDefaultInstanceForType() {
        return com.grpcserver.product.ProductServer.Product.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpcserver.product.ProductServer.Product build() {
        com.grpcserver.product.ProductServer.Product result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpcserver.product.ProductServer.Product buildPartial() {
        com.grpcserver.product.ProductServer.Product result = new com.grpcserver.product.ProductServer.Product(this);
        result.purchaseItem_ = purchaseItem_;
        result.productname_ = productname_;
        result.productbrand_ = productbrand_;
        result.productprice_ = productprice_;
        result.productdescription_ = productdescription_;
        result.productquantity_ = productquantity_;
        result.productexpirationdate_ = productexpirationdate_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpcserver.product.ProductServer.Product) {
          return mergeFrom((com.grpcserver.product.ProductServer.Product)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpcserver.product.ProductServer.Product other) {
        if (other == com.grpcserver.product.ProductServer.Product.getDefaultInstance()) return this;
        if (other.getPurchaseItem() != 0) {
          setPurchaseItem(other.getPurchaseItem());
        }
        if (!other.getProductname().isEmpty()) {
          productname_ = other.productname_;
          onChanged();
        }
        if (!other.getProductbrand().isEmpty()) {
          productbrand_ = other.productbrand_;
          onChanged();
        }
        if (other.getProductprice() != 0D) {
          setProductprice(other.getProductprice());
        }
        if (!other.getProductdescription().isEmpty()) {
          productdescription_ = other.productdescription_;
          onChanged();
        }
        if (other.getProductquantity() != 0) {
          setProductquantity(other.getProductquantity());
        }
        if (!other.getProductexpirationdate().isEmpty()) {
          productexpirationdate_ = other.productexpirationdate_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.grpcserver.product.ProductServer.Product parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.grpcserver.product.ProductServer.Product) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int purchaseItem_ ;
      /**
       * <code>int32 purchase_item = 1;</code>
       */
      public int getPurchaseItem() {
        return purchaseItem_;
      }
      /**
       * <code>int32 purchase_item = 1;</code>
       */
      public Builder setPurchaseItem(int value) {
        
        purchaseItem_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 purchase_item = 1;</code>
       */
      public Builder clearPurchaseItem() {
        
        purchaseItem_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object productname_ = "";
      /**
       * <code>string productname = 2;</code>
       */
      public java.lang.String getProductname() {
        java.lang.Object ref = productname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          productname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string productname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getProductnameBytes() {
        java.lang.Object ref = productname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string productname = 2;</code>
       */
      public Builder setProductname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        productname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string productname = 2;</code>
       */
      public Builder clearProductname() {
        
        productname_ = getDefaultInstance().getProductname();
        onChanged();
        return this;
      }
      /**
       * <code>string productname = 2;</code>
       */
      public Builder setProductnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        productname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object productbrand_ = "";
      /**
       * <code>string productbrand = 3;</code>
       */
      public java.lang.String getProductbrand() {
        java.lang.Object ref = productbrand_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          productbrand_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string productbrand = 3;</code>
       */
      public com.google.protobuf.ByteString
          getProductbrandBytes() {
        java.lang.Object ref = productbrand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productbrand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string productbrand = 3;</code>
       */
      public Builder setProductbrand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        productbrand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string productbrand = 3;</code>
       */
      public Builder clearProductbrand() {
        
        productbrand_ = getDefaultInstance().getProductbrand();
        onChanged();
        return this;
      }
      /**
       * <code>string productbrand = 3;</code>
       */
      public Builder setProductbrandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        productbrand_ = value;
        onChanged();
        return this;
      }

      private double productprice_ ;
      /**
       * <code>double productprice = 4;</code>
       */
      public double getProductprice() {
        return productprice_;
      }
      /**
       * <code>double productprice = 4;</code>
       */
      public Builder setProductprice(double value) {
        
        productprice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double productprice = 4;</code>
       */
      public Builder clearProductprice() {
        
        productprice_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object productdescription_ = "";
      /**
       * <code>string productdescription = 5;</code>
       */
      public java.lang.String getProductdescription() {
        java.lang.Object ref = productdescription_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          productdescription_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string productdescription = 5;</code>
       */
      public com.google.protobuf.ByteString
          getProductdescriptionBytes() {
        java.lang.Object ref = productdescription_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productdescription_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string productdescription = 5;</code>
       */
      public Builder setProductdescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        productdescription_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string productdescription = 5;</code>
       */
      public Builder clearProductdescription() {
        
        productdescription_ = getDefaultInstance().getProductdescription();
        onChanged();
        return this;
      }
      /**
       * <code>string productdescription = 5;</code>
       */
      public Builder setProductdescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        productdescription_ = value;
        onChanged();
        return this;
      }

      private int productquantity_ ;
      /**
       * <code>int32 productquantity = 6;</code>
       */
      public int getProductquantity() {
        return productquantity_;
      }
      /**
       * <code>int32 productquantity = 6;</code>
       */
      public Builder setProductquantity(int value) {
        
        productquantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 productquantity = 6;</code>
       */
      public Builder clearProductquantity() {
        
        productquantity_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object productexpirationdate_ = "";
      /**
       * <code>string productexpirationdate = 8;</code>
       */
      public java.lang.String getProductexpirationdate() {
        java.lang.Object ref = productexpirationdate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          productexpirationdate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string productexpirationdate = 8;</code>
       */
      public com.google.protobuf.ByteString
          getProductexpirationdateBytes() {
        java.lang.Object ref = productexpirationdate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productexpirationdate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string productexpirationdate = 8;</code>
       */
      public Builder setProductexpirationdate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        productexpirationdate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string productexpirationdate = 8;</code>
       */
      public Builder clearProductexpirationdate() {
        
        productexpirationdate_ = getDefaultInstance().getProductexpirationdate();
        onChanged();
        return this;
      }
      /**
       * <code>string productexpirationdate = 8;</code>
       */
      public Builder setProductexpirationdateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        productexpirationdate_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Product)
    }

    // @@protoc_insertion_point(class_scope:Product)
    private static final com.grpcserver.product.ProductServer.Product DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpcserver.product.ProductServer.Product();
    }

    public static com.grpcserver.product.ProductServer.Product getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Product>
        PARSER = new com.google.protobuf.AbstractParser<Product>() {
      @java.lang.Override
      public Product parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Product(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Product> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Product> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpcserver.product.ProductServer.Product getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProductListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProductList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Product product = 1;</code>
     */
    java.util.List<com.grpcserver.product.ProductServer.Product> 
        getProductList();
    /**
     * <code>repeated .Product product = 1;</code>
     */
    com.grpcserver.product.ProductServer.Product getProduct(int index);
    /**
     * <code>repeated .Product product = 1;</code>
     */
    int getProductCount();
    /**
     * <code>repeated .Product product = 1;</code>
     */
    java.util.List<? extends com.grpcserver.product.ProductServer.ProductOrBuilder> 
        getProductOrBuilderList();
    /**
     * <code>repeated .Product product = 1;</code>
     */
    com.grpcserver.product.ProductServer.ProductOrBuilder getProductOrBuilder(
        int index);

    /**
     * <code>.google.protobuf.Int64Value resultCount = 2;</code>
     */
    boolean hasResultCount();
    /**
     * <code>.google.protobuf.Int64Value resultCount = 2;</code>
     */
    com.google.protobuf.Int64Value getResultCount();
    /**
     * <code>.google.protobuf.Int64Value resultCount = 2;</code>
     */
    com.google.protobuf.Int64ValueOrBuilder getResultCountOrBuilder();
  }
  /**
   * Protobuf type {@code ProductList}
   */
  public  static final class ProductList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ProductList)
      ProductListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProductList.newBuilder() to construct.
    private ProductList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProductList() {
      product_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProductList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                product_ = new java.util.ArrayList<com.grpcserver.product.ProductServer.Product>();
                mutable_bitField0_ |= 0x00000001;
              }
              product_.add(
                  input.readMessage(com.grpcserver.product.ProductServer.Product.parser(), extensionRegistry));
              break;
            }
            case 18: {
              com.google.protobuf.Int64Value.Builder subBuilder = null;
              if (resultCount_ != null) {
                subBuilder = resultCount_.toBuilder();
              }
              resultCount_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(resultCount_);
                resultCount_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          product_ = java.util.Collections.unmodifiableList(product_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpcserver.product.ProductServer.internal_static_ProductList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpcserver.product.ProductServer.internal_static_ProductList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpcserver.product.ProductServer.ProductList.class, com.grpcserver.product.ProductServer.ProductList.Builder.class);
    }

    private int bitField0_;
    public static final int PRODUCT_FIELD_NUMBER = 1;
    private java.util.List<com.grpcserver.product.ProductServer.Product> product_;
    /**
     * <code>repeated .Product product = 1;</code>
     */
    public java.util.List<com.grpcserver.product.ProductServer.Product> getProductList() {
      return product_;
    }
    /**
     * <code>repeated .Product product = 1;</code>
     */
    public java.util.List<? extends com.grpcserver.product.ProductServer.ProductOrBuilder> 
        getProductOrBuilderList() {
      return product_;
    }
    /**
     * <code>repeated .Product product = 1;</code>
     */
    public int getProductCount() {
      return product_.size();
    }
    /**
     * <code>repeated .Product product = 1;</code>
     */
    public com.grpcserver.product.ProductServer.Product getProduct(int index) {
      return product_.get(index);
    }
    /**
     * <code>repeated .Product product = 1;</code>
     */
    public com.grpcserver.product.ProductServer.ProductOrBuilder getProductOrBuilder(
        int index) {
      return product_.get(index);
    }

    public static final int RESULTCOUNT_FIELD_NUMBER = 2;
    private com.google.protobuf.Int64Value resultCount_;
    /**
     * <code>.google.protobuf.Int64Value resultCount = 2;</code>
     */
    public boolean hasResultCount() {
      return resultCount_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value resultCount = 2;</code>
     */
    public com.google.protobuf.Int64Value getResultCount() {
      return resultCount_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : resultCount_;
    }
    /**
     * <code>.google.protobuf.Int64Value resultCount = 2;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getResultCountOrBuilder() {
      return getResultCount();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < product_.size(); i++) {
        output.writeMessage(1, product_.get(i));
      }
      if (resultCount_ != null) {
        output.writeMessage(2, getResultCount());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < product_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, product_.get(i));
      }
      if (resultCount_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getResultCount());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpcserver.product.ProductServer.ProductList)) {
        return super.equals(obj);
      }
      com.grpcserver.product.ProductServer.ProductList other = (com.grpcserver.product.ProductServer.ProductList) obj;

      boolean result = true;
      result = result && getProductList()
          .equals(other.getProductList());
      result = result && (hasResultCount() == other.hasResultCount());
      if (hasResultCount()) {
        result = result && getResultCount()
            .equals(other.getResultCount());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getProductCount() > 0) {
        hash = (37 * hash) + PRODUCT_FIELD_NUMBER;
        hash = (53 * hash) + getProductList().hashCode();
      }
      if (hasResultCount()) {
        hash = (37 * hash) + RESULTCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getResultCount().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpcserver.product.ProductServer.ProductList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcserver.product.ProductServer.ProductList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcserver.product.ProductServer.ProductList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcserver.product.ProductServer.ProductList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcserver.product.ProductServer.ProductList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcserver.product.ProductServer.ProductList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcserver.product.ProductServer.ProductList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcserver.product.ProductServer.ProductList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpcserver.product.ProductServer.ProductList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.grpcserver.product.ProductServer.ProductList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpcserver.product.ProductServer.ProductList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcserver.product.ProductServer.ProductList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpcserver.product.ProductServer.ProductList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProductList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProductList)
        com.grpcserver.product.ProductServer.ProductListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpcserver.product.ProductServer.internal_static_ProductList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpcserver.product.ProductServer.internal_static_ProductList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpcserver.product.ProductServer.ProductList.class, com.grpcserver.product.ProductServer.ProductList.Builder.class);
      }

      // Construct using com.grpcserver.product.ProductServer.ProductList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getProductFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (productBuilder_ == null) {
          product_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          productBuilder_.clear();
        }
        if (resultCountBuilder_ == null) {
          resultCount_ = null;
        } else {
          resultCount_ = null;
          resultCountBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpcserver.product.ProductServer.internal_static_ProductList_descriptor;
      }

      @java.lang.Override
      public com.grpcserver.product.ProductServer.ProductList getDefaultInstanceForType() {
        return com.grpcserver.product.ProductServer.ProductList.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpcserver.product.ProductServer.ProductList build() {
        com.grpcserver.product.ProductServer.ProductList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpcserver.product.ProductServer.ProductList buildPartial() {
        com.grpcserver.product.ProductServer.ProductList result = new com.grpcserver.product.ProductServer.ProductList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (productBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            product_ = java.util.Collections.unmodifiableList(product_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.product_ = product_;
        } else {
          result.product_ = productBuilder_.build();
        }
        if (resultCountBuilder_ == null) {
          result.resultCount_ = resultCount_;
        } else {
          result.resultCount_ = resultCountBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpcserver.product.ProductServer.ProductList) {
          return mergeFrom((com.grpcserver.product.ProductServer.ProductList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpcserver.product.ProductServer.ProductList other) {
        if (other == com.grpcserver.product.ProductServer.ProductList.getDefaultInstance()) return this;
        if (productBuilder_ == null) {
          if (!other.product_.isEmpty()) {
            if (product_.isEmpty()) {
              product_ = other.product_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureProductIsMutable();
              product_.addAll(other.product_);
            }
            onChanged();
          }
        } else {
          if (!other.product_.isEmpty()) {
            if (productBuilder_.isEmpty()) {
              productBuilder_.dispose();
              productBuilder_ = null;
              product_ = other.product_;
              bitField0_ = (bitField0_ & ~0x00000001);
              productBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getProductFieldBuilder() : null;
            } else {
              productBuilder_.addAllMessages(other.product_);
            }
          }
        }
        if (other.hasResultCount()) {
          mergeResultCount(other.getResultCount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.grpcserver.product.ProductServer.ProductList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.grpcserver.product.ProductServer.ProductList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.grpcserver.product.ProductServer.Product> product_ =
        java.util.Collections.emptyList();
      private void ensureProductIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          product_ = new java.util.ArrayList<com.grpcserver.product.ProductServer.Product>(product_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.grpcserver.product.ProductServer.Product, com.grpcserver.product.ProductServer.Product.Builder, com.grpcserver.product.ProductServer.ProductOrBuilder> productBuilder_;

      /**
       * <code>repeated .Product product = 1;</code>
       */
      public java.util.List<com.grpcserver.product.ProductServer.Product> getProductList() {
        if (productBuilder_ == null) {
          return java.util.Collections.unmodifiableList(product_);
        } else {
          return productBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public int getProductCount() {
        if (productBuilder_ == null) {
          return product_.size();
        } else {
          return productBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public com.grpcserver.product.ProductServer.Product getProduct(int index) {
        if (productBuilder_ == null) {
          return product_.get(index);
        } else {
          return productBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public Builder setProduct(
          int index, com.grpcserver.product.ProductServer.Product value) {
        if (productBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductIsMutable();
          product_.set(index, value);
          onChanged();
        } else {
          productBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public Builder setProduct(
          int index, com.grpcserver.product.ProductServer.Product.Builder builderForValue) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          product_.set(index, builderForValue.build());
          onChanged();
        } else {
          productBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public Builder addProduct(com.grpcserver.product.ProductServer.Product value) {
        if (productBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductIsMutable();
          product_.add(value);
          onChanged();
        } else {
          productBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public Builder addProduct(
          int index, com.grpcserver.product.ProductServer.Product value) {
        if (productBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductIsMutable();
          product_.add(index, value);
          onChanged();
        } else {
          productBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public Builder addProduct(
          com.grpcserver.product.ProductServer.Product.Builder builderForValue) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          product_.add(builderForValue.build());
          onChanged();
        } else {
          productBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public Builder addProduct(
          int index, com.grpcserver.product.ProductServer.Product.Builder builderForValue) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          product_.add(index, builderForValue.build());
          onChanged();
        } else {
          productBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public Builder addAllProduct(
          java.lang.Iterable<? extends com.grpcserver.product.ProductServer.Product> values) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, product_);
          onChanged();
        } else {
          productBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public Builder clearProduct() {
        if (productBuilder_ == null) {
          product_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          productBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public Builder removeProduct(int index) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          product_.remove(index);
          onChanged();
        } else {
          productBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public com.grpcserver.product.ProductServer.Product.Builder getProductBuilder(
          int index) {
        return getProductFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public com.grpcserver.product.ProductServer.ProductOrBuilder getProductOrBuilder(
          int index) {
        if (productBuilder_ == null) {
          return product_.get(index);  } else {
          return productBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public java.util.List<? extends com.grpcserver.product.ProductServer.ProductOrBuilder> 
           getProductOrBuilderList() {
        if (productBuilder_ != null) {
          return productBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(product_);
        }
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public com.grpcserver.product.ProductServer.Product.Builder addProductBuilder() {
        return getProductFieldBuilder().addBuilder(
            com.grpcserver.product.ProductServer.Product.getDefaultInstance());
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public com.grpcserver.product.ProductServer.Product.Builder addProductBuilder(
          int index) {
        return getProductFieldBuilder().addBuilder(
            index, com.grpcserver.product.ProductServer.Product.getDefaultInstance());
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public java.util.List<com.grpcserver.product.ProductServer.Product.Builder> 
           getProductBuilderList() {
        return getProductFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.grpcserver.product.ProductServer.Product, com.grpcserver.product.ProductServer.Product.Builder, com.grpcserver.product.ProductServer.ProductOrBuilder> 
          getProductFieldBuilder() {
        if (productBuilder_ == null) {
          productBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.grpcserver.product.ProductServer.Product, com.grpcserver.product.ProductServer.Product.Builder, com.grpcserver.product.ProductServer.ProductOrBuilder>(
                  product_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          product_ = null;
        }
        return productBuilder_;
      }

      private com.google.protobuf.Int64Value resultCount_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> resultCountBuilder_;
      /**
       * <code>.google.protobuf.Int64Value resultCount = 2;</code>
       */
      public boolean hasResultCount() {
        return resultCountBuilder_ != null || resultCount_ != null;
      }
      /**
       * <code>.google.protobuf.Int64Value resultCount = 2;</code>
       */
      public com.google.protobuf.Int64Value getResultCount() {
        if (resultCountBuilder_ == null) {
          return resultCount_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : resultCount_;
        } else {
          return resultCountBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Int64Value resultCount = 2;</code>
       */
      public Builder setResultCount(com.google.protobuf.Int64Value value) {
        if (resultCountBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          resultCount_ = value;
          onChanged();
        } else {
          resultCountBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int64Value resultCount = 2;</code>
       */
      public Builder setResultCount(
          com.google.protobuf.Int64Value.Builder builderForValue) {
        if (resultCountBuilder_ == null) {
          resultCount_ = builderForValue.build();
          onChanged();
        } else {
          resultCountBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int64Value resultCount = 2;</code>
       */
      public Builder mergeResultCount(com.google.protobuf.Int64Value value) {
        if (resultCountBuilder_ == null) {
          if (resultCount_ != null) {
            resultCount_ =
              com.google.protobuf.Int64Value.newBuilder(resultCount_).mergeFrom(value).buildPartial();
          } else {
            resultCount_ = value;
          }
          onChanged();
        } else {
          resultCountBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int64Value resultCount = 2;</code>
       */
      public Builder clearResultCount() {
        if (resultCountBuilder_ == null) {
          resultCount_ = null;
          onChanged();
        } else {
          resultCount_ = null;
          resultCountBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int64Value resultCount = 2;</code>
       */
      public com.google.protobuf.Int64Value.Builder getResultCountBuilder() {
        
        onChanged();
        return getResultCountFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Int64Value resultCount = 2;</code>
       */
      public com.google.protobuf.Int64ValueOrBuilder getResultCountOrBuilder() {
        if (resultCountBuilder_ != null) {
          return resultCountBuilder_.getMessageOrBuilder();
        } else {
          return resultCount_ == null ?
              com.google.protobuf.Int64Value.getDefaultInstance() : resultCount_;
        }
      }
      /**
       * <code>.google.protobuf.Int64Value resultCount = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
          getResultCountFieldBuilder() {
        if (resultCountBuilder_ == null) {
          resultCountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                  getResultCount(),
                  getParentForChildren(),
                  isClean());
          resultCount_ = null;
        }
        return resultCountBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ProductList)
    }

    // @@protoc_insertion_point(class_scope:ProductList)
    private static final com.grpcserver.product.ProductServer.ProductList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpcserver.product.ProductServer.ProductList();
    }

    public static com.grpcserver.product.ProductServer.ProductList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProductList>
        PARSER = new com.google.protobuf.AbstractParser<ProductList>() {
      @java.lang.Override
      public ProductList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProductList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProductList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProductList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpcserver.product.ProductServer.ProductList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface APIResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:APIResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string responsemessage = 1;</code>
     */
    java.lang.String getResponsemessage();
    /**
     * <code>string responsemessage = 1;</code>
     */
    com.google.protobuf.ByteString
        getResponsemessageBytes();

    /**
     * <code>int32 responseCode = 2;</code>
     */
    int getResponseCode();
  }
  /**
   * Protobuf type {@code APIResponse}
   */
  public  static final class APIResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:APIResponse)
      APIResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use APIResponse.newBuilder() to construct.
    private APIResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private APIResponse() {
      responsemessage_ = "";
      responseCode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private APIResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              responsemessage_ = s;
              break;
            }
            case 16: {

              responseCode_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpcserver.product.ProductServer.internal_static_APIResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpcserver.product.ProductServer.internal_static_APIResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpcserver.product.ProductServer.APIResponse.class, com.grpcserver.product.ProductServer.APIResponse.Builder.class);
    }

    public static final int RESPONSEMESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object responsemessage_;
    /**
     * <code>string responsemessage = 1;</code>
     */
    public java.lang.String getResponsemessage() {
      java.lang.Object ref = responsemessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responsemessage_ = s;
        return s;
      }
    }
    /**
     * <code>string responsemessage = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResponsemessageBytes() {
      java.lang.Object ref = responsemessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responsemessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESPONSECODE_FIELD_NUMBER = 2;
    private int responseCode_;
    /**
     * <code>int32 responseCode = 2;</code>
     */
    public int getResponseCode() {
      return responseCode_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResponsemessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, responsemessage_);
      }
      if (responseCode_ != 0) {
        output.writeInt32(2, responseCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResponsemessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, responsemessage_);
      }
      if (responseCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, responseCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpcserver.product.ProductServer.APIResponse)) {
        return super.equals(obj);
      }
      com.grpcserver.product.ProductServer.APIResponse other = (com.grpcserver.product.ProductServer.APIResponse) obj;

      boolean result = true;
      result = result && getResponsemessage()
          .equals(other.getResponsemessage());
      result = result && (getResponseCode()
          == other.getResponseCode());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSEMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getResponsemessage().hashCode();
      hash = (37 * hash) + RESPONSECODE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpcserver.product.ProductServer.APIResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcserver.product.ProductServer.APIResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcserver.product.ProductServer.APIResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcserver.product.ProductServer.APIResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcserver.product.ProductServer.APIResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcserver.product.ProductServer.APIResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcserver.product.ProductServer.APIResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcserver.product.ProductServer.APIResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpcserver.product.ProductServer.APIResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.grpcserver.product.ProductServer.APIResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpcserver.product.ProductServer.APIResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcserver.product.ProductServer.APIResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpcserver.product.ProductServer.APIResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code APIResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:APIResponse)
        com.grpcserver.product.ProductServer.APIResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpcserver.product.ProductServer.internal_static_APIResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpcserver.product.ProductServer.internal_static_APIResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpcserver.product.ProductServer.APIResponse.class, com.grpcserver.product.ProductServer.APIResponse.Builder.class);
      }

      // Construct using com.grpcserver.product.ProductServer.APIResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responsemessage_ = "";

        responseCode_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpcserver.product.ProductServer.internal_static_APIResponse_descriptor;
      }

      @java.lang.Override
      public com.grpcserver.product.ProductServer.APIResponse getDefaultInstanceForType() {
        return com.grpcserver.product.ProductServer.APIResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpcserver.product.ProductServer.APIResponse build() {
        com.grpcserver.product.ProductServer.APIResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpcserver.product.ProductServer.APIResponse buildPartial() {
        com.grpcserver.product.ProductServer.APIResponse result = new com.grpcserver.product.ProductServer.APIResponse(this);
        result.responsemessage_ = responsemessage_;
        result.responseCode_ = responseCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpcserver.product.ProductServer.APIResponse) {
          return mergeFrom((com.grpcserver.product.ProductServer.APIResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpcserver.product.ProductServer.APIResponse other) {
        if (other == com.grpcserver.product.ProductServer.APIResponse.getDefaultInstance()) return this;
        if (!other.getResponsemessage().isEmpty()) {
          responsemessage_ = other.responsemessage_;
          onChanged();
        }
        if (other.getResponseCode() != 0) {
          setResponseCode(other.getResponseCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.grpcserver.product.ProductServer.APIResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.grpcserver.product.ProductServer.APIResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object responsemessage_ = "";
      /**
       * <code>string responsemessage = 1;</code>
       */
      public java.lang.String getResponsemessage() {
        java.lang.Object ref = responsemessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responsemessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string responsemessage = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResponsemessageBytes() {
        java.lang.Object ref = responsemessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responsemessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string responsemessage = 1;</code>
       */
      public Builder setResponsemessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responsemessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string responsemessage = 1;</code>
       */
      public Builder clearResponsemessage() {
        
        responsemessage_ = getDefaultInstance().getResponsemessage();
        onChanged();
        return this;
      }
      /**
       * <code>string responsemessage = 1;</code>
       */
      public Builder setResponsemessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responsemessage_ = value;
        onChanged();
        return this;
      }

      private int responseCode_ ;
      /**
       * <code>int32 responseCode = 2;</code>
       */
      public int getResponseCode() {
        return responseCode_;
      }
      /**
       * <code>int32 responseCode = 2;</code>
       */
      public Builder setResponseCode(int value) {
        
        responseCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 responseCode = 2;</code>
       */
      public Builder clearResponseCode() {
        
        responseCode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:APIResponse)
    }

    // @@protoc_insertion_point(class_scope:APIResponse)
    private static final com.grpcserver.product.ProductServer.APIResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpcserver.product.ProductServer.APIResponse();
    }

    public static com.grpcserver.product.ProductServer.APIResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<APIResponse>
        PARSER = new com.google.protobuf.AbstractParser<APIResponse>() {
      @java.lang.Override
      public APIResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new APIResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<APIResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<APIResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpcserver.product.ProductServer.APIResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Product_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Product_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_APIResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_APIResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ProductServer.proto\032\036google/protobuf/w" +
      "rappers.proto\032\033google/protobuf/empty.pro" +
      "to\"\265\001\n\007Product\022\025\n\rpurchase_item\030\001 \001(\005\022\023\n" +
      "\013productname\030\002 \001(\t\022\024\n\014productbrand\030\003 \001(\t" +
      "\022\024\n\014productprice\030\004 \001(\001\022\032\n\022productdescrip" +
      "tion\030\005 \001(\t\022\027\n\017productquantity\030\006 \001(\005\022\035\n\025p" +
      "roductexpirationdate\030\010 \001(\t\"Z\n\013ProductLis" +
      "t\022\031\n\007product\030\001 \003(\0132\010.Product\0220\n\013resultCo" +
      "unt\030\002 \001(\0132\033.google.protobuf.Int64Value\"<" +
      "\n\013APIResponse\022\027\n\017responsemessage\030\001 \001(\t\022\024" +
      "\n\014responseCode\030\002 \001(\0052\330\001\n\016ProductService\022" +
      ")\n\017findAllRepeated\022\010.Product\032\014.ProductLi" +
      "st\022 \n\006insert\022\010.Product\032\014.APIResponse\022$\n\n" +
      "deleteById\022\010.Product\032\014.APIResponse\0221\n\010fi" +
      "ndById\022\033.google.protobuf.Int32Value\032\010.Pr" +
      "oduct\022 \n\006update\022\010.Product\032\014.APIResponseB" +
      "\030\n\026com.grpcserver.productb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_Product_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Product_descriptor,
        new java.lang.String[] { "PurchaseItem", "Productname", "Productbrand", "Productprice", "Productdescription", "Productquantity", "Productexpirationdate", });
    internal_static_ProductList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProductList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductList_descriptor,
        new java.lang.String[] { "Product", "ResultCount", });
    internal_static_APIResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_APIResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_APIResponse_descriptor,
        new java.lang.String[] { "Responsemessage", "ResponseCode", });
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
