// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductServer.proto

package com.grpcserver;

public final class ProductServer {
  private ProductServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Empty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code Empty}
   */
  public  static final class Empty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Empty)
      EmptyOrBuilder {
    // Use Empty.newBuilder() to construct.
    private Empty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Empty() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Empty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpcserver.ProductServer.internal_static_Empty_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpcserver.ProductServer.internal_static_Empty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpcserver.ProductServer.Empty.class, com.grpcserver.ProductServer.Empty.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpcserver.ProductServer.Empty)) {
        return super.equals(obj);
      }
      com.grpcserver.ProductServer.Empty other = (com.grpcserver.ProductServer.Empty) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpcserver.ProductServer.Empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcserver.ProductServer.Empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcserver.ProductServer.Empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcserver.ProductServer.Empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcserver.ProductServer.Empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcserver.ProductServer.Empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpcserver.ProductServer.Empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.grpcserver.ProductServer.Empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpcserver.ProductServer.Empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcserver.ProductServer.Empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpcserver.ProductServer.Empty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Empty)
        com.grpcserver.ProductServer.EmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpcserver.ProductServer.internal_static_Empty_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpcserver.ProductServer.internal_static_Empty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpcserver.ProductServer.Empty.class, com.grpcserver.ProductServer.Empty.Builder.class);
      }

      // Construct using com.grpcserver.ProductServer.Empty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpcserver.ProductServer.internal_static_Empty_descriptor;
      }

      public com.grpcserver.ProductServer.Empty getDefaultInstanceForType() {
        return com.grpcserver.ProductServer.Empty.getDefaultInstance();
      }

      public com.grpcserver.ProductServer.Empty build() {
        com.grpcserver.ProductServer.Empty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.grpcserver.ProductServer.Empty buildPartial() {
        com.grpcserver.ProductServer.Empty result = new com.grpcserver.ProductServer.Empty(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpcserver.ProductServer.Empty) {
          return mergeFrom((com.grpcserver.ProductServer.Empty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpcserver.ProductServer.Empty other) {
        if (other == com.grpcserver.ProductServer.Empty.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.grpcserver.ProductServer.Empty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.grpcserver.ProductServer.Empty) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Empty)
    }

    // @@protoc_insertion_point(class_scope:Empty)
    private static final com.grpcserver.ProductServer.Empty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpcserver.ProductServer.Empty();
    }

    public static com.grpcserver.ProductServer.Empty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Empty>
        PARSER = new com.google.protobuf.AbstractParser<Empty>() {
      public Empty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Empty(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Empty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Empty> getParserForType() {
      return PARSER;
    }

    public com.grpcserver.ProductServer.Empty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProductOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Product)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 purchase_item = 1;</code>
     */
    int getPurchaseItem();

    /**
     * <code>optional string productname = 2;</code>
     */
    java.lang.String getProductname();
    /**
     * <code>optional string productname = 2;</code>
     */
    com.google.protobuf.ByteString
        getProductnameBytes();

    /**
     * <code>optional string productbrand = 3;</code>
     */
    java.lang.String getProductbrand();
    /**
     * <code>optional string productbrand = 3;</code>
     */
    com.google.protobuf.ByteString
        getProductbrandBytes();

    /**
     * <code>optional double productprice = 4;</code>
     */
    double getProductprice();

    /**
     * <code>optional string productdescription = 5;</code>
     */
    java.lang.String getProductdescription();
    /**
     * <code>optional string productdescription = 5;</code>
     */
    com.google.protobuf.ByteString
        getProductdescriptionBytes();

    /**
     * <code>optional int32 productquantity = 6;</code>
     */
    int getProductquantity();

    /**
     * <code>optional .google.protobuf.Timestamp productcurrentdate = 7;</code>
     */
    boolean hasProductcurrentdate();
    /**
     * <code>optional .google.protobuf.Timestamp productcurrentdate = 7;</code>
     */
    com.google.protobuf.Timestamp getProductcurrentdate();
    /**
     * <code>optional .google.protobuf.Timestamp productcurrentdate = 7;</code>
     */
    com.google.protobuf.TimestampOrBuilder getProductcurrentdateOrBuilder();

    /**
     * <code>optional .google.protobuf.Timestamp productexpirationdate = 8;</code>
     */
    boolean hasProductexpirationdate();
    /**
     * <code>optional .google.protobuf.Timestamp productexpirationdate = 8;</code>
     */
    com.google.protobuf.Timestamp getProductexpirationdate();
    /**
     * <code>optional .google.protobuf.Timestamp productexpirationdate = 8;</code>
     */
    com.google.protobuf.TimestampOrBuilder getProductexpirationdateOrBuilder();
  }
  /**
   * Protobuf type {@code Product}
   */
  public  static final class Product extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Product)
      ProductOrBuilder {
    // Use Product.newBuilder() to construct.
    private Product(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Product() {
      purchaseItem_ = 0;
      productname_ = "";
      productbrand_ = "";
      productprice_ = 0D;
      productdescription_ = "";
      productquantity_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Product(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              purchaseItem_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              productname_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              productbrand_ = s;
              break;
            }
            case 33: {

              productprice_ = input.readDouble();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              productdescription_ = s;
              break;
            }
            case 48: {

              productquantity_ = input.readInt32();
              break;
            }
            case 58: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (productcurrentdate_ != null) {
                subBuilder = productcurrentdate_.toBuilder();
              }
              productcurrentdate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(productcurrentdate_);
                productcurrentdate_ = subBuilder.buildPartial();
              }

              break;
            }
            case 66: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (productexpirationdate_ != null) {
                subBuilder = productexpirationdate_.toBuilder();
              }
              productexpirationdate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(productexpirationdate_);
                productexpirationdate_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpcserver.ProductServer.internal_static_Product_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpcserver.ProductServer.internal_static_Product_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpcserver.ProductServer.Product.class, com.grpcserver.ProductServer.Product.Builder.class);
    }

    public static final int PURCHASE_ITEM_FIELD_NUMBER = 1;
    private int purchaseItem_;
    /**
     * <code>optional int32 purchase_item = 1;</code>
     */
    public int getPurchaseItem() {
      return purchaseItem_;
    }

    public static final int PRODUCTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object productname_;
    /**
     * <code>optional string productname = 2;</code>
     */
    public java.lang.String getProductname() {
      java.lang.Object ref = productname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productname_ = s;
        return s;
      }
    }
    /**
     * <code>optional string productname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProductnameBytes() {
      java.lang.Object ref = productname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCTBRAND_FIELD_NUMBER = 3;
    private volatile java.lang.Object productbrand_;
    /**
     * <code>optional string productbrand = 3;</code>
     */
    public java.lang.String getProductbrand() {
      java.lang.Object ref = productbrand_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productbrand_ = s;
        return s;
      }
    }
    /**
     * <code>optional string productbrand = 3;</code>
     */
    public com.google.protobuf.ByteString
        getProductbrandBytes() {
      java.lang.Object ref = productbrand_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productbrand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCTPRICE_FIELD_NUMBER = 4;
    private double productprice_;
    /**
     * <code>optional double productprice = 4;</code>
     */
    public double getProductprice() {
      return productprice_;
    }

    public static final int PRODUCTDESCRIPTION_FIELD_NUMBER = 5;
    private volatile java.lang.Object productdescription_;
    /**
     * <code>optional string productdescription = 5;</code>
     */
    public java.lang.String getProductdescription() {
      java.lang.Object ref = productdescription_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productdescription_ = s;
        return s;
      }
    }
    /**
     * <code>optional string productdescription = 5;</code>
     */
    public com.google.protobuf.ByteString
        getProductdescriptionBytes() {
      java.lang.Object ref = productdescription_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productdescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCTQUANTITY_FIELD_NUMBER = 6;
    private int productquantity_;
    /**
     * <code>optional int32 productquantity = 6;</code>
     */
    public int getProductquantity() {
      return productquantity_;
    }

    public static final int PRODUCTCURRENTDATE_FIELD_NUMBER = 7;
    private com.google.protobuf.Timestamp productcurrentdate_;
    /**
     * <code>optional .google.protobuf.Timestamp productcurrentdate = 7;</code>
     */
    public boolean hasProductcurrentdate() {
      return productcurrentdate_ != null;
    }
    /**
     * <code>optional .google.protobuf.Timestamp productcurrentdate = 7;</code>
     */
    public com.google.protobuf.Timestamp getProductcurrentdate() {
      return productcurrentdate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : productcurrentdate_;
    }
    /**
     * <code>optional .google.protobuf.Timestamp productcurrentdate = 7;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getProductcurrentdateOrBuilder() {
      return getProductcurrentdate();
    }

    public static final int PRODUCTEXPIRATIONDATE_FIELD_NUMBER = 8;
    private com.google.protobuf.Timestamp productexpirationdate_;
    /**
     * <code>optional .google.protobuf.Timestamp productexpirationdate = 8;</code>
     */
    public boolean hasProductexpirationdate() {
      return productexpirationdate_ != null;
    }
    /**
     * <code>optional .google.protobuf.Timestamp productexpirationdate = 8;</code>
     */
    public com.google.protobuf.Timestamp getProductexpirationdate() {
      return productexpirationdate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : productexpirationdate_;
    }
    /**
     * <code>optional .google.protobuf.Timestamp productexpirationdate = 8;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getProductexpirationdateOrBuilder() {
      return getProductexpirationdate();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (purchaseItem_ != 0) {
        output.writeInt32(1, purchaseItem_);
      }
      if (!getProductnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, productname_);
      }
      if (!getProductbrandBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, productbrand_);
      }
      if (productprice_ != 0D) {
        output.writeDouble(4, productprice_);
      }
      if (!getProductdescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, productdescription_);
      }
      if (productquantity_ != 0) {
        output.writeInt32(6, productquantity_);
      }
      if (productcurrentdate_ != null) {
        output.writeMessage(7, getProductcurrentdate());
      }
      if (productexpirationdate_ != null) {
        output.writeMessage(8, getProductexpirationdate());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (purchaseItem_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, purchaseItem_);
      }
      if (!getProductnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, productname_);
      }
      if (!getProductbrandBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, productbrand_);
      }
      if (productprice_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, productprice_);
      }
      if (!getProductdescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, productdescription_);
      }
      if (productquantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, productquantity_);
      }
      if (productcurrentdate_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getProductcurrentdate());
      }
      if (productexpirationdate_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getProductexpirationdate());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpcserver.ProductServer.Product)) {
        return super.equals(obj);
      }
      com.grpcserver.ProductServer.Product other = (com.grpcserver.ProductServer.Product) obj;

      boolean result = true;
      result = result && (getPurchaseItem()
          == other.getPurchaseItem());
      result = result && getProductname()
          .equals(other.getProductname());
      result = result && getProductbrand()
          .equals(other.getProductbrand());
      result = result && (
          java.lang.Double.doubleToLongBits(getProductprice())
          == java.lang.Double.doubleToLongBits(
              other.getProductprice()));
      result = result && getProductdescription()
          .equals(other.getProductdescription());
      result = result && (getProductquantity()
          == other.getProductquantity());
      result = result && (hasProductcurrentdate() == other.hasProductcurrentdate());
      if (hasProductcurrentdate()) {
        result = result && getProductcurrentdate()
            .equals(other.getProductcurrentdate());
      }
      result = result && (hasProductexpirationdate() == other.hasProductexpirationdate());
      if (hasProductexpirationdate()) {
        result = result && getProductexpirationdate()
            .equals(other.getProductexpirationdate());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PURCHASE_ITEM_FIELD_NUMBER;
      hash = (53 * hash) + getPurchaseItem();
      hash = (37 * hash) + PRODUCTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getProductname().hashCode();
      hash = (37 * hash) + PRODUCTBRAND_FIELD_NUMBER;
      hash = (53 * hash) + getProductbrand().hashCode();
      hash = (37 * hash) + PRODUCTPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getProductprice()));
      hash = (37 * hash) + PRODUCTDESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getProductdescription().hashCode();
      hash = (37 * hash) + PRODUCTQUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getProductquantity();
      if (hasProductcurrentdate()) {
        hash = (37 * hash) + PRODUCTCURRENTDATE_FIELD_NUMBER;
        hash = (53 * hash) + getProductcurrentdate().hashCode();
      }
      if (hasProductexpirationdate()) {
        hash = (37 * hash) + PRODUCTEXPIRATIONDATE_FIELD_NUMBER;
        hash = (53 * hash) + getProductexpirationdate().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpcserver.ProductServer.Product parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcserver.ProductServer.Product parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcserver.ProductServer.Product parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcserver.ProductServer.Product parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcserver.ProductServer.Product parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcserver.ProductServer.Product parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpcserver.ProductServer.Product parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.grpcserver.ProductServer.Product parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpcserver.ProductServer.Product parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcserver.ProductServer.Product parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpcserver.ProductServer.Product prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Product}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Product)
        com.grpcserver.ProductServer.ProductOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpcserver.ProductServer.internal_static_Product_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpcserver.ProductServer.internal_static_Product_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpcserver.ProductServer.Product.class, com.grpcserver.ProductServer.Product.Builder.class);
      }

      // Construct using com.grpcserver.ProductServer.Product.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        purchaseItem_ = 0;

        productname_ = "";

        productbrand_ = "";

        productprice_ = 0D;

        productdescription_ = "";

        productquantity_ = 0;

        if (productcurrentdateBuilder_ == null) {
          productcurrentdate_ = null;
        } else {
          productcurrentdate_ = null;
          productcurrentdateBuilder_ = null;
        }
        if (productexpirationdateBuilder_ == null) {
          productexpirationdate_ = null;
        } else {
          productexpirationdate_ = null;
          productexpirationdateBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpcserver.ProductServer.internal_static_Product_descriptor;
      }

      public com.grpcserver.ProductServer.Product getDefaultInstanceForType() {
        return com.grpcserver.ProductServer.Product.getDefaultInstance();
      }

      public com.grpcserver.ProductServer.Product build() {
        com.grpcserver.ProductServer.Product result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.grpcserver.ProductServer.Product buildPartial() {
        com.grpcserver.ProductServer.Product result = new com.grpcserver.ProductServer.Product(this);
        result.purchaseItem_ = purchaseItem_;
        result.productname_ = productname_;
        result.productbrand_ = productbrand_;
        result.productprice_ = productprice_;
        result.productdescription_ = productdescription_;
        result.productquantity_ = productquantity_;
        if (productcurrentdateBuilder_ == null) {
          result.productcurrentdate_ = productcurrentdate_;
        } else {
          result.productcurrentdate_ = productcurrentdateBuilder_.build();
        }
        if (productexpirationdateBuilder_ == null) {
          result.productexpirationdate_ = productexpirationdate_;
        } else {
          result.productexpirationdate_ = productexpirationdateBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpcserver.ProductServer.Product) {
          return mergeFrom((com.grpcserver.ProductServer.Product)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpcserver.ProductServer.Product other) {
        if (other == com.grpcserver.ProductServer.Product.getDefaultInstance()) return this;
        if (other.getPurchaseItem() != 0) {
          setPurchaseItem(other.getPurchaseItem());
        }
        if (!other.getProductname().isEmpty()) {
          productname_ = other.productname_;
          onChanged();
        }
        if (!other.getProductbrand().isEmpty()) {
          productbrand_ = other.productbrand_;
          onChanged();
        }
        if (other.getProductprice() != 0D) {
          setProductprice(other.getProductprice());
        }
        if (!other.getProductdescription().isEmpty()) {
          productdescription_ = other.productdescription_;
          onChanged();
        }
        if (other.getProductquantity() != 0) {
          setProductquantity(other.getProductquantity());
        }
        if (other.hasProductcurrentdate()) {
          mergeProductcurrentdate(other.getProductcurrentdate());
        }
        if (other.hasProductexpirationdate()) {
          mergeProductexpirationdate(other.getProductexpirationdate());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.grpcserver.ProductServer.Product parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.grpcserver.ProductServer.Product) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int purchaseItem_ ;
      /**
       * <code>optional int32 purchase_item = 1;</code>
       */
      public int getPurchaseItem() {
        return purchaseItem_;
      }
      /**
       * <code>optional int32 purchase_item = 1;</code>
       */
      public Builder setPurchaseItem(int value) {
        
        purchaseItem_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 purchase_item = 1;</code>
       */
      public Builder clearPurchaseItem() {
        
        purchaseItem_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object productname_ = "";
      /**
       * <code>optional string productname = 2;</code>
       */
      public java.lang.String getProductname() {
        java.lang.Object ref = productname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          productname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string productname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getProductnameBytes() {
        java.lang.Object ref = productname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string productname = 2;</code>
       */
      public Builder setProductname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        productname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string productname = 2;</code>
       */
      public Builder clearProductname() {
        
        productname_ = getDefaultInstance().getProductname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string productname = 2;</code>
       */
      public Builder setProductnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        productname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object productbrand_ = "";
      /**
       * <code>optional string productbrand = 3;</code>
       */
      public java.lang.String getProductbrand() {
        java.lang.Object ref = productbrand_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          productbrand_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string productbrand = 3;</code>
       */
      public com.google.protobuf.ByteString
          getProductbrandBytes() {
        java.lang.Object ref = productbrand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productbrand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string productbrand = 3;</code>
       */
      public Builder setProductbrand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        productbrand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string productbrand = 3;</code>
       */
      public Builder clearProductbrand() {
        
        productbrand_ = getDefaultInstance().getProductbrand();
        onChanged();
        return this;
      }
      /**
       * <code>optional string productbrand = 3;</code>
       */
      public Builder setProductbrandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        productbrand_ = value;
        onChanged();
        return this;
      }

      private double productprice_ ;
      /**
       * <code>optional double productprice = 4;</code>
       */
      public double getProductprice() {
        return productprice_;
      }
      /**
       * <code>optional double productprice = 4;</code>
       */
      public Builder setProductprice(double value) {
        
        productprice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double productprice = 4;</code>
       */
      public Builder clearProductprice() {
        
        productprice_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object productdescription_ = "";
      /**
       * <code>optional string productdescription = 5;</code>
       */
      public java.lang.String getProductdescription() {
        java.lang.Object ref = productdescription_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          productdescription_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string productdescription = 5;</code>
       */
      public com.google.protobuf.ByteString
          getProductdescriptionBytes() {
        java.lang.Object ref = productdescription_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productdescription_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string productdescription = 5;</code>
       */
      public Builder setProductdescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        productdescription_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string productdescription = 5;</code>
       */
      public Builder clearProductdescription() {
        
        productdescription_ = getDefaultInstance().getProductdescription();
        onChanged();
        return this;
      }
      /**
       * <code>optional string productdescription = 5;</code>
       */
      public Builder setProductdescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        productdescription_ = value;
        onChanged();
        return this;
      }

      private int productquantity_ ;
      /**
       * <code>optional int32 productquantity = 6;</code>
       */
      public int getProductquantity() {
        return productquantity_;
      }
      /**
       * <code>optional int32 productquantity = 6;</code>
       */
      public Builder setProductquantity(int value) {
        
        productquantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 productquantity = 6;</code>
       */
      public Builder clearProductquantity() {
        
        productquantity_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp productcurrentdate_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> productcurrentdateBuilder_;
      /**
       * <code>optional .google.protobuf.Timestamp productcurrentdate = 7;</code>
       */
      public boolean hasProductcurrentdate() {
        return productcurrentdateBuilder_ != null || productcurrentdate_ != null;
      }
      /**
       * <code>optional .google.protobuf.Timestamp productcurrentdate = 7;</code>
       */
      public com.google.protobuf.Timestamp getProductcurrentdate() {
        if (productcurrentdateBuilder_ == null) {
          return productcurrentdate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : productcurrentdate_;
        } else {
          return productcurrentdateBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp productcurrentdate = 7;</code>
       */
      public Builder setProductcurrentdate(com.google.protobuf.Timestamp value) {
        if (productcurrentdateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          productcurrentdate_ = value;
          onChanged();
        } else {
          productcurrentdateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp productcurrentdate = 7;</code>
       */
      public Builder setProductcurrentdate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (productcurrentdateBuilder_ == null) {
          productcurrentdate_ = builderForValue.build();
          onChanged();
        } else {
          productcurrentdateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp productcurrentdate = 7;</code>
       */
      public Builder mergeProductcurrentdate(com.google.protobuf.Timestamp value) {
        if (productcurrentdateBuilder_ == null) {
          if (productcurrentdate_ != null) {
            productcurrentdate_ =
              com.google.protobuf.Timestamp.newBuilder(productcurrentdate_).mergeFrom(value).buildPartial();
          } else {
            productcurrentdate_ = value;
          }
          onChanged();
        } else {
          productcurrentdateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp productcurrentdate = 7;</code>
       */
      public Builder clearProductcurrentdate() {
        if (productcurrentdateBuilder_ == null) {
          productcurrentdate_ = null;
          onChanged();
        } else {
          productcurrentdate_ = null;
          productcurrentdateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp productcurrentdate = 7;</code>
       */
      public com.google.protobuf.Timestamp.Builder getProductcurrentdateBuilder() {
        
        onChanged();
        return getProductcurrentdateFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.Timestamp productcurrentdate = 7;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getProductcurrentdateOrBuilder() {
        if (productcurrentdateBuilder_ != null) {
          return productcurrentdateBuilder_.getMessageOrBuilder();
        } else {
          return productcurrentdate_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : productcurrentdate_;
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp productcurrentdate = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getProductcurrentdateFieldBuilder() {
        if (productcurrentdateBuilder_ == null) {
          productcurrentdateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getProductcurrentdate(),
                  getParentForChildren(),
                  isClean());
          productcurrentdate_ = null;
        }
        return productcurrentdateBuilder_;
      }

      private com.google.protobuf.Timestamp productexpirationdate_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> productexpirationdateBuilder_;
      /**
       * <code>optional .google.protobuf.Timestamp productexpirationdate = 8;</code>
       */
      public boolean hasProductexpirationdate() {
        return productexpirationdateBuilder_ != null || productexpirationdate_ != null;
      }
      /**
       * <code>optional .google.protobuf.Timestamp productexpirationdate = 8;</code>
       */
      public com.google.protobuf.Timestamp getProductexpirationdate() {
        if (productexpirationdateBuilder_ == null) {
          return productexpirationdate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : productexpirationdate_;
        } else {
          return productexpirationdateBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp productexpirationdate = 8;</code>
       */
      public Builder setProductexpirationdate(com.google.protobuf.Timestamp value) {
        if (productexpirationdateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          productexpirationdate_ = value;
          onChanged();
        } else {
          productexpirationdateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp productexpirationdate = 8;</code>
       */
      public Builder setProductexpirationdate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (productexpirationdateBuilder_ == null) {
          productexpirationdate_ = builderForValue.build();
          onChanged();
        } else {
          productexpirationdateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp productexpirationdate = 8;</code>
       */
      public Builder mergeProductexpirationdate(com.google.protobuf.Timestamp value) {
        if (productexpirationdateBuilder_ == null) {
          if (productexpirationdate_ != null) {
            productexpirationdate_ =
              com.google.protobuf.Timestamp.newBuilder(productexpirationdate_).mergeFrom(value).buildPartial();
          } else {
            productexpirationdate_ = value;
          }
          onChanged();
        } else {
          productexpirationdateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp productexpirationdate = 8;</code>
       */
      public Builder clearProductexpirationdate() {
        if (productexpirationdateBuilder_ == null) {
          productexpirationdate_ = null;
          onChanged();
        } else {
          productexpirationdate_ = null;
          productexpirationdateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp productexpirationdate = 8;</code>
       */
      public com.google.protobuf.Timestamp.Builder getProductexpirationdateBuilder() {
        
        onChanged();
        return getProductexpirationdateFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.Timestamp productexpirationdate = 8;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getProductexpirationdateOrBuilder() {
        if (productexpirationdateBuilder_ != null) {
          return productexpirationdateBuilder_.getMessageOrBuilder();
        } else {
          return productexpirationdate_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : productexpirationdate_;
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp productexpirationdate = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getProductexpirationdateFieldBuilder() {
        if (productexpirationdateBuilder_ == null) {
          productexpirationdateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getProductexpirationdate(),
                  getParentForChildren(),
                  isClean());
          productexpirationdate_ = null;
        }
        return productexpirationdateBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Product)
    }

    // @@protoc_insertion_point(class_scope:Product)
    private static final com.grpcserver.ProductServer.Product DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpcserver.ProductServer.Product();
    }

    public static com.grpcserver.ProductServer.Product getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Product>
        PARSER = new com.google.protobuf.AbstractParser<Product>() {
      public Product parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Product(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Product> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Product> getParserForType() {
      return PARSER;
    }

    public com.grpcserver.ProductServer.Product getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface APIResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:APIResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string responsemessage = 1;</code>
     */
    java.lang.String getResponsemessage();
    /**
     * <code>optional string responsemessage = 1;</code>
     */
    com.google.protobuf.ByteString
        getResponsemessageBytes();

    /**
     * <code>optional int32 responseCode = 2;</code>
     */
    int getResponseCode();
  }
  /**
   * Protobuf type {@code APIResponse}
   */
  public  static final class APIResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:APIResponse)
      APIResponseOrBuilder {
    // Use APIResponse.newBuilder() to construct.
    private APIResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private APIResponse() {
      responsemessage_ = "";
      responseCode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private APIResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              responsemessage_ = s;
              break;
            }
            case 16: {

              responseCode_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpcserver.ProductServer.internal_static_APIResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpcserver.ProductServer.internal_static_APIResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpcserver.ProductServer.APIResponse.class, com.grpcserver.ProductServer.APIResponse.Builder.class);
    }

    public static final int RESPONSEMESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object responsemessage_;
    /**
     * <code>optional string responsemessage = 1;</code>
     */
    public java.lang.String getResponsemessage() {
      java.lang.Object ref = responsemessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responsemessage_ = s;
        return s;
      }
    }
    /**
     * <code>optional string responsemessage = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResponsemessageBytes() {
      java.lang.Object ref = responsemessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responsemessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESPONSECODE_FIELD_NUMBER = 2;
    private int responseCode_;
    /**
     * <code>optional int32 responseCode = 2;</code>
     */
    public int getResponseCode() {
      return responseCode_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResponsemessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, responsemessage_);
      }
      if (responseCode_ != 0) {
        output.writeInt32(2, responseCode_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResponsemessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, responsemessage_);
      }
      if (responseCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, responseCode_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpcserver.ProductServer.APIResponse)) {
        return super.equals(obj);
      }
      com.grpcserver.ProductServer.APIResponse other = (com.grpcserver.ProductServer.APIResponse) obj;

      boolean result = true;
      result = result && getResponsemessage()
          .equals(other.getResponsemessage());
      result = result && (getResponseCode()
          == other.getResponseCode());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + RESPONSEMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getResponsemessage().hashCode();
      hash = (37 * hash) + RESPONSECODE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpcserver.ProductServer.APIResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcserver.ProductServer.APIResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcserver.ProductServer.APIResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcserver.ProductServer.APIResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcserver.ProductServer.APIResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcserver.ProductServer.APIResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpcserver.ProductServer.APIResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.grpcserver.ProductServer.APIResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpcserver.ProductServer.APIResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcserver.ProductServer.APIResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpcserver.ProductServer.APIResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code APIResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:APIResponse)
        com.grpcserver.ProductServer.APIResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpcserver.ProductServer.internal_static_APIResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpcserver.ProductServer.internal_static_APIResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpcserver.ProductServer.APIResponse.class, com.grpcserver.ProductServer.APIResponse.Builder.class);
      }

      // Construct using com.grpcserver.ProductServer.APIResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        responsemessage_ = "";

        responseCode_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpcserver.ProductServer.internal_static_APIResponse_descriptor;
      }

      public com.grpcserver.ProductServer.APIResponse getDefaultInstanceForType() {
        return com.grpcserver.ProductServer.APIResponse.getDefaultInstance();
      }

      public com.grpcserver.ProductServer.APIResponse build() {
        com.grpcserver.ProductServer.APIResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.grpcserver.ProductServer.APIResponse buildPartial() {
        com.grpcserver.ProductServer.APIResponse result = new com.grpcserver.ProductServer.APIResponse(this);
        result.responsemessage_ = responsemessage_;
        result.responseCode_ = responseCode_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpcserver.ProductServer.APIResponse) {
          return mergeFrom((com.grpcserver.ProductServer.APIResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpcserver.ProductServer.APIResponse other) {
        if (other == com.grpcserver.ProductServer.APIResponse.getDefaultInstance()) return this;
        if (!other.getResponsemessage().isEmpty()) {
          responsemessage_ = other.responsemessage_;
          onChanged();
        }
        if (other.getResponseCode() != 0) {
          setResponseCode(other.getResponseCode());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.grpcserver.ProductServer.APIResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.grpcserver.ProductServer.APIResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object responsemessage_ = "";
      /**
       * <code>optional string responsemessage = 1;</code>
       */
      public java.lang.String getResponsemessage() {
        java.lang.Object ref = responsemessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responsemessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string responsemessage = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResponsemessageBytes() {
        java.lang.Object ref = responsemessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responsemessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string responsemessage = 1;</code>
       */
      public Builder setResponsemessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responsemessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string responsemessage = 1;</code>
       */
      public Builder clearResponsemessage() {
        
        responsemessage_ = getDefaultInstance().getResponsemessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string responsemessage = 1;</code>
       */
      public Builder setResponsemessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responsemessage_ = value;
        onChanged();
        return this;
      }

      private int responseCode_ ;
      /**
       * <code>optional int32 responseCode = 2;</code>
       */
      public int getResponseCode() {
        return responseCode_;
      }
      /**
       * <code>optional int32 responseCode = 2;</code>
       */
      public Builder setResponseCode(int value) {
        
        responseCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 responseCode = 2;</code>
       */
      public Builder clearResponseCode() {
        
        responseCode_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:APIResponse)
    }

    // @@protoc_insertion_point(class_scope:APIResponse)
    private static final com.grpcserver.ProductServer.APIResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpcserver.ProductServer.APIResponse();
    }

    public static com.grpcserver.ProductServer.APIResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<APIResponse>
        PARSER = new com.google.protobuf.AbstractParser<APIResponse>() {
      public APIResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new APIResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<APIResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<APIResponse> getParserForType() {
      return PARSER;
    }

    public com.grpcserver.ProductServer.APIResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Product_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Product_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_APIResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_APIResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ProductServer.proto\032\036google/protobuf/w" +
      "rappers.proto\032\037google/protobuf/timestamp" +
      ".proto\"\007\n\005Empty\"\211\002\n\007Product\022\025\n\rpurchase_" +
      "item\030\001 \001(\005\022\023\n\013productname\030\002 \001(\t\022\024\n\014produ" +
      "ctbrand\030\003 \001(\t\022\024\n\014productprice\030\004 \001(\001\022\032\n\022p" +
      "roductdescription\030\005 \001(\t\022\027\n\017productquanti" +
      "ty\030\006 \001(\005\0226\n\022productcurrentdate\030\007 \001(\0132\032.g" +
      "oogle.protobuf.Timestamp\0229\n\025productexpir" +
      "ationdate\030\010 \001(\0132\032.google.protobuf.Timest" +
      "amp\"<\n\013APIResponse\022\027\n\017responsemessage\030\001 ",
      "\001(\t\022\024\n\014responseCode\030\002 \001(\0052\311\001\n\013ClientGues" +
      "t\022 \n\006insert\022\010.Product\032\014.APIResponse\022\035\n\007f" +
      "indAll\022\006.Empty\032\010.Product0\001\022$\n\ndeleteById" +
      "\022\010.Product\032\014.APIResponse\0221\n\010findById\022\033.g" +
      "oogle.protobuf.Int32Value\032\010.Product\022 \n\006u" +
      "pdate\022\010.Product\032\014.APIResponseB\020\n\016com.grp" +
      "cserverb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_Product_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Product_descriptor,
        new java.lang.String[] { "PurchaseItem", "Productname", "Productbrand", "Productprice", "Productdescription", "Productquantity", "Productcurrentdate", "Productexpirationdate", });
    internal_static_APIResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_APIResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_APIResponse_descriptor,
        new java.lang.String[] { "Responsemessage", "ResponseCode", });
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
