version: '3.8'


networks:
  default:
    name: product-poc-project-net
    external: true


services:

  cartservice:
    image: cartservice:latest
    container_name: cartservice
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    
    ports: 
      - "9090:9090"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      GRPC-SERVER-PORT: 9090


