version: '3.8'


services:
  cartgatewayservice:
    image: cartgatewayservice:latest
    container_name: cartgatewayservice
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9000:8094
    environment:
      SERVER_PORT: 8094
      GRPC-SERVER-PORT: 9090
      GRPC-SERVER_HOST: cartservice
     