version: '3.8'


networks:
  default:
    name: product-poc-project-net
    external: true

services:
  cartgatewayservice:
    image: cartgatewayservice:latest
    container_name: cartgatewayservice
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9009:8094"
    