version: '3.8'

networks:
  default:
    name: product-poc-project-net
    external: true
    
services: 
#----------------------------------------------------------------  
  productmicroservice:
    image: productmicroservice:latest
    container_name: productmicroservice
     
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9001:8091"
    
    environment:
    
      - MYSQL_HOST=cart-mysqldb
      - MYSQL_USER=oot
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
      
      - "SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE}"
    
      
    
#----------------------------------------------------------------      

#   product-mysqldb:
 #    image: mysql:8.0.28
  #   restart: unless-stopped
  #   container_name: product-mysqldb
  #   ports: 
   #    - "3307:3306"
    
   #  cap_add:
   #    - SYS_NICE
   #  environment:
   #    MYSQL_DATABASE: dbpoc
   #   MYSQL_ROOT_PASSWORD: root
    
      
#----------------------------------------------------------------   

        
  zookeeper:
    image: elevy/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
   
     
    
      
      
#----------------------------------------------------------------
 
    
  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    container_name: kafka
    
    restart: on-failure

    ports:
      - "9092:9092"
      - "9093:9093"
      
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "producttopic:1:1"
      
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
    depends_on:
      - zookeeper
    
    
    
      

    
      
  