version: '3'


services: 
  ProductMicroservice:
    image: productmicroservice
    restart: always
    build: .
    ports:
      - "8093:8093"
    networks:
      - product-net
    depends_on:
      - kafka
      - mysqldb
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
  mysqldb: 
    image: mysql:8.0.28
    restart: unless-stopped
    container_name: mysqldb
    ports: 
      - "3307:3306"
    cap_add:
      - SYS_NICE
    networks:
      - product-net 
    environment:
      MYSQL_DATABASE: dbpoc
      MYSQL_ROOT_PASSWORD: root  
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    networks:
      - product-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kakfa:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    networks:
      - product-net
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper 
networks:
    product-net:
      driver: bridge   