version: '3.8'

networks:
  default:
    name: product-poc-project-net
    external: true
    
services: 
#----------------------------------------------------------------  
  productmicroservice:
    image: productmicroservice:latest
    container_name: productmicroservice
     
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9001:8091"
    
    environment:
    
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
      
      - "SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE}"
    
   
      

    
      
  