version: '3.8'

networks:
  default:
    name: product-poc-project-net
    external: true

services:
  kongapigateway:
    image: kongapigateway:latest
    container_name: kongapigateway
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8099:8095
      
