server:
   port: 8095 



spring:
  main:
   allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    default-property-inclusion: NON_NULL
    deserialization:
      wrap-exceptions: false


