
cloud:
  aws:
    credentials:
      access-key: secret6
      secret-key: secret6
    region:
      static: us-west-1
      use-default-aws-region-chain: true
    stack:
      auto: false

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  main:
    allow-bean-definition-overriding: true
      
      
