spring:
  mvc:
   throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
        
  sql:
    init:
      mode: always
      continue-on-error: true


 






       
  

      