spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/dbpoc
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
  
  jackson:
    default-property-inclusion:  NON_NULL
         
  sql:
    init:
      mode: always
      continue-on-error: true
      
  mvc:
   throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

actable:
  table:
    auto: update
  model:
    pack: com.cartservice.Model
  database:
    type: mysql
    
mybatis:
  table:
    auto: update

grpc:
  server:
     port: ${GRPC-SERVER-PORT:9090} 
     


log4j:
   appender:
    file:
      layout: org.apache.log4j.PatternLayout
      ConversionPattern: "%d %p %t %c %m"
  
   

  