version: '3.8'

networks:
  default:
    name: product-poc-project-net
    external: true

services:
  loggermicroservice:
    image: loggermicroservice
    container_name: loggermicroservice
    build:
     context: ./
     dockerfile: Dockerfile
    ports: 
      - 8087:80
            

