version: '3.8'

networks:
  default:
    name: product-poc-project-net
    external: true

services:
  loggermicroservice:
    image: loggermicroservice
    container_name: loggermicroservice
    build:
     context: ./
     dockerfile: Dockerfile
    ports: 
      - 8087:80
    depends_on:
      - mongodb
    
    
      
    
    
   
 #----------------------------------------------------------------     
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: LoggerActivity
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

#----------------------------------------------------------------   
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express 
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/"
    depends_on:
      - mongodb
            

