version: '3.8'

services:

  loggermicroservice:
     image: loggermicroservice
     container_name: loggermicroservice
     build:
      context: ./
      dockerfile: Dockerfile
     ports:
      - 8082:8082
     depends_on:
      - mongodb
  mongodb:
       image: mongo:latest
       container_name: mongodb
       ports:
         - 27018:27017
       restart: always

       environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
 
  mongo-express:
       image: mongo-express:latest
       container_name: mongo-express 
       restart: always
       ports:
          - 8081:8082
       environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
            ME_CONFIG_MONGODB_SERVER: mongodb
            

   





